
List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': "NYC", 'name': "New York"},
    'to': {'code': "LDN", 'name': "London"},
    'flying_time': '8H 30M',
    'date': '1 May',
    'departure_time': '8:00 AM',
    'number': '23A',
  },
  {
    'from': {'code': "DEL", 'name': "Delhi"},
    'to': {'code': "DXB", 'name': "Dubai"},
    'flying_time': '3H 45M',
    'date': '10 June',
    'departure_time': '6:30 PM',
    'number': '47B',
  },
  {
    'from': {'code': "SFO", 'name': "San Francisco"},
    'to': {'code': "SYD", 'name': "Sydney"},
    'flying_time': '15H 20M',
    'date': '22 July',
    'departure_time': '10:15 AM',
    'number': '89C',
  },
  {
    'from': {'code': "BOM", 'name': "Mumbai"},
    'to': {'code': "SIN", 'name': "Singapore"},
    'flying_time': '5H 30M',
    'date': '5 August',
    'departure_time': '9:45 PM',
    'number': '12D',
  },
  {
    'from': {'code': "LAX", 'name': "Los Angeles"},
    'to': {'code': "JFK", 'name': "New York"},
    'flying_time': '5H 50M',
    'date': '15 March',
    'departure_time': '7:30 AM',
    'number': '58E',
  },
  {
    'from': {'code': "CDG", 'name': "Paris"},
    'to': {'code': "AMS", 'name': "Amsterdam"},
    'flying_time': '1H 20M',
    'date': '8 April',
    'departure_time': '1:00 PM',
    'number': '33F',
  },
  {
    'from': {'code': "HND", 'name': "Tokyo"},
    'to': {'code': "ICN", 'name': "Seoul"},
    'flying_time': '2H 15M',
    'date': '18 September',
    'departure_time': '11:00 AM',
    'number': '90G',
  },
  {
    'from': {'code': "MAD", 'name': "Madrid"},
    'to': {'code': "BCN", 'name': "Barcelona"},
    'flying_time': '1H 05M',
    'date': '2 October',
    'departure_time': '4:00 PM',
    'number': '21H',
  },
  {
    'from': {'code': "FRA", 'name': "Frankfurt"},
    'to': {'code': "ZRH", 'name': "Zurich"},
    'flying_time': '1H 10M',
    'date': '12 November',
    'departure_time': '9:00 AM',
    'number': '76I',
  },
  {
    'from': {'code': "GRU", 'name': "São Paulo"},
    'to': {'code': "EZE", 'name': "Buenos Aires"},
    'flying_time': '2H 45M',
    'date': '29 December',
    'departure_time': '2:30 PM',
    'number': '105J',
  },
];


List<Map<String, dynamic>> hotelList = [
  {
    'image': 'city_view.png',
    'place': 'One Space',
    'destination': 'New York',
    'price': 25,
  },
  {
    'image': 'city_view.png',
    'place': 'Sunset Resort',
    'destination': 'Malibu',
    'price': 120,
  },
  {
    'image': 'city_view.png',
    'place': 'Mountain Inn',
    'destination': 'Denver',
    'price': 80,
  },
  {
    'image': 'city_view.png',
    'place': 'Cityscape Hotel',
    'destination': 'Chicago',
    'price': 100,
  },
  {
    'image': 'city_view.png',
    'place': 'Beachside Bungalow',
    'destination': 'Miami',
    'price': 90,
  },
  {
    'image': 'city_view.png',
    'place': 'Royal Palace',
    'destination': 'Las Vegas',
    'price': 150,
  },
];
